package apriorigeneric; 
import java.util.*;
import javax.swing.UIManager;
import javax.swing.border.EtchedBorder;
import javax.swing.border.TitledBorder;
import javax.swing.*;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField; 
/** * * @author CHANDINI 
*/
public class AprioriFE4772 extends javax.swing.JFrame { 
	/** 
* Creates new form AprioriG 
*/ 
public AprioriFE4772() { 
	
	setSize(1000,1000);
	setLocationRelativeTo ( null );
initComponents(); 
} 
/** 
* This method is called from within the constructor to initialize the form. 
* WARNING: Do NOT modify this code. The content of this method is always 
* regenerated by the Form Editor. 
*/ 

private void initComponents() { 
	
labelApriori = new javax.swing.JLabel(); 
labelOutput = new javax.swing.JLabel(); 
labelSupport = new javax.swing.JLabel();
labelConfidence = new javax.swing.JLabel();
textSupport = new javax.swing.JTextField(); //
textConfidence = new javax.swing.JTextField();
myoutput=new JTable();

buttonCalculate = new javax.swing.JButton(); 
labelDB = new javax.swing.JLabel(); 
textDB = new javax.swing.JTextField(); 
textOutput = new javax.swing.JTextArea(35,58);

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 
labelApriori.setText("CS634 Apriori Algorithm by Chandini Ganesan");
labelOutput.setText("Output");
labelConfidence.setText("Select DB to process");
labelSupport.setText("Enter Support Threshold"); 
buttonCalculate.setText("Calculate"); 

//ScrollBar
JPanel middlePanel = new JPanel ();
textOutput.setEditable ( false ); // set textArea non-editable
JScrollPane scroll = new JScrollPane ( textOutput );
scroll.setVerticalScrollBarPolicy ( ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS );
middlePanel.add ( scroll );


buttonCalculate.addActionListener(new java.awt.event.ActionListener() { 
public void actionPerformed(java.awt.event.ActionEvent evt) { 
buttonCalculateActionPerformed(evt); 
} 
}); 
labelDB.setText("Enter Confidence Threshold "); 
javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); 
getContentPane().setLayout(layout); 
//my horizontal
layout.setHorizontalGroup( 
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
.addGroup(layout.createSequentialGroup() 
.addContainerGap() 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
.addComponent(labelSupport) 
.addComponent(labelDB)
.addComponent(labelConfidence)
.addComponent(labelOutput)) 
.addGap(70, 70, 70) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
		.addComponent(labelApriori) 
		.addComponent(textSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 74, 
				javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(textDB, javax.swing.GroupLayout.PREFERRED_SIZE, 74, 
javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(textConfidence, javax.swing.GroupLayout.PREFERRED_SIZE, 74, 
javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(middlePanel)
		)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
		.addComponent(buttonCalculate) )
)
); 

//my Vertical
layout.setVerticalGroup( 
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 
.addGroup(layout.createSequentialGroup() 
.addGap(30, 30, 30) 
.addComponent(labelApriori) 
.addGap(45, 45, 45) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 
.addComponent(labelSupport) 
.addComponent(textSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) 
.addComponent(buttonCalculate)) 
.addGap(34, 34, 34) 
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 
.addComponent(labelDB) 
.addComponent(textDB, javax.swing.GroupLayout.PREFERRED_SIZE, 
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)) 
.addGap(34, 34, 34)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 
		.addComponent(labelConfidence) 
		.addComponent(textConfidence, javax.swing.GroupLayout.PREFERRED_SIZE, //line
javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(34, 34, 34)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 
		.addComponent(labelOutput) 
		.addComponent(middlePanel))
) 
); 

}// End of Init


private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) { 
 
	textOutput.setText("");
float supportThreshold,confThres;
String dbname;
List<DescribeItem> tL = new ArrayList<>(); 
supportThreshold = Integer.parseInt(textSupport.getText()); 
confThres = Integer.parseInt(textDB.getText()); 
dbname=textConfidence.getText();
System.out.println(); 
int i=1; 
AprioriBE4772 aG = new AprioriBE4772(supportThreshold,dbname); 
tL = aG.getTranscDetail(); 
do{ 
tL=aG.getCombo(tL,tL); 
i++; 
} 
while(tL.size()>1); 
aG.AssociateRule(confThres); 
String op=aG.getOutput();
String [] temp = op.split("\n"); 
for (String s : temp)
textOutput.setText(textOutput.getText()+"\n"+s);
} 
/** 
* @param args the command line arguments 
*/ 
public static void main(String args[]) { 

//</editor-fold> 
/* Create and display the form */ 
} 
private javax.swing.JButton buttonCalculate; 
private javax.swing.JLabel labelApriori; 
private javax.swing.JLabel labelSupport; 
private javax.swing.JLabel labelConfidence;
private javax.swing.JLabel labelDB;
private javax.swing.JLabel labelOutput;
private javax.swing.JTextField textSupport; 
private javax.swing.JTextField textConfidence; 
private javax.swing.JTextField textDB; 
private javax.swing.JTextArea textOutput;
private javax.swing.JTable myoutput;
// End of variables declaration 
} 
